// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozhwaslhcrkdmownsvot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96aHdhc2xoY3JrZG1vd25zdm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTQwMDAsImV4cCI6MjA1ODczMDAwMH0.mPT5z632iAY5X3MnY_ZbguKkYKxPNQje55-8DTNNRlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);